//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class AudLogAccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AudLogAccion()
        {
            this.PryAuditoria = new HashSet<PryAuditoria>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Accion_Id { get; set; }
        public string AccionTo { get; set; }
        public string AccionToId { get; set; }
        public Nullable<int> Access_Id { get; set; }
        public string Data { get; set; }
        public Nullable<int> DynamicDataSet_Id { get; set; }
        public string Ip { get; set; }
        public Nullable<int> idPryProyecto { get; set; }
        public int ProyectoId { get; set; }
    
        public virtual AudAccion AudAccion { get; set; }
        public virtual SegAccess SegAccess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PryAuditoria> PryAuditoria { get; set; }
        public virtual PryProyecto PryProyecto { get; set; }
        public virtual SegUser SegUser { get; set; }
    }
}
