//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicActaObra
    {
        public int idLicActaObra { get; set; }
        public Nullable<int> idObra { get; set; }
        public string actaEncabezado { get; set; }
        public string actaFormal { get; set; }
        public string actaOferta { get; set; }
        public string actaCierre { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
        public Nullable<int> idUsuarioAlta { get; set; }
        public Nullable<System.DateTime> fechaModif { get; set; }
        public Nullable<int> idUsuarioModif { get; set; }
        public string cuadroResumen { get; set; }
        public string cuadroOferta { get; set; }
    }
}
