//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicArchivoEmpresa
    {
        public int idArchivo { get; set; }
        public Nullable<int> idObra { get; set; }
        public Nullable<int> idEmpresa { get; set; }
        public string cuit { get; set; }
        public Nullable<int> idRequisito { get; set; }
        public string nombreArchivo { get; set; }
        public string ruta { get; set; }
        public string clave { get; set; }
        public string nombreArchivoEnc { get; set; }
        public string rutaVirtual { get; set; }
        public Nullable<int> nroSobre { get; set; }
        public Nullable<int> idEstadoArchivo { get; set; }
        public string observaciones { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string tipoArchivo { get; set; }
        public string hora { get; set; }
        public Nullable<int> enviado { get; set; }
        public Nullable<int> tipoOferta { get; set; }
        public Nullable<int> esFracasada { get; set; }
    }
}
