//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicCalificacionChatbot
    {
        public int idLicCalificacionChatbot { get; set; }
        public Nullable<System.DateTime> FechaCalificacion { get; set; }
        public Nullable<bool> Util { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> IdEscenario { get; set; }
        public Nullable<int> IdPregunta { get; set; }
    }
}
