//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicDocSobres
    {
        public int idLicDocSobres { get; set; }
        public Nullable<int> numero { get; set; }
        public string nombre { get; set; }
        public Nullable<int> idObra { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> esFracasada { get; set; }
    }
}
