//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicDocObra
    {
        public int idLicDocObra { get; set; }
        public Nullable<int> idObra { get; set; }
        public Nullable<int> idDocumentacion { get; set; }
        public Nullable<int> nroSobre { get; set; }
        public Nullable<int> esFracasada { get; set; }
    }
}
