//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicEscenarioChatbot
    {
        public int idLicEscenarioChatbot { get; set; }
        public string NombreEscenario { get; set; }
        public string Sector { get; set; }
        public string Descripcion { get; set; }
        public Nullable<sbyte> Activo { get; set; }
    }
}
