//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicOferta
    {
        public int idLicOferta { get; set; }
        public Nullable<int> idObra { get; set; }
        public Nullable<int> idEmpresa { get; set; }
        public Nullable<int> fechaOferta { get; set; }
        public Nullable<decimal> montoOferta { get; set; }
        public Nullable<int> idEstadoOferta { get; set; }
    }
}
