//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicProyectoFecha
    {
        public int idLicProyectoFecha { get; set; }
        public Nullable<int> idProyecto { get; set; }
        public Nullable<System.DateTime> fechaPublicacion { get; set; }
        public Nullable<System.DateTime> fechaCierre { get; set; }
        public Nullable<System.DateTime> fechaApertura { get; set; }
        public string horaApertura { get; set; }
        public Nullable<int> esFracasada { get; set; }
    }
}
