//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicProyecto
    {
        public int idLicProyecto { get; set; }
        public int idProyecto { get; set; }
        public Nullable<int> moneda { get; set; }
        public string urlPliego { get; set; }
        public string mailConsulta { get; set; }
        public Nullable<System.DateTime> limiteConsulta { get; set; }
        public string domicilioPresentacion { get; set; }
        public string domicilioApertura { get; set; }
        public Nullable<System.DateTime> fechaVisita { get; set; }
        public string lugarVisita { get; set; }
        public Nullable<System.DateTime> fechaCierre { get; set; }
        public Nullable<int> idUsuarioModif { get; set; }
        public Nullable<System.DateTime> fechaModif { get; set; }
        public string domicilioVirtual { get; set; }
        public Nullable<System.DateTime> fechaVtoObs { get; set; }
        public string horaVtoObs { get; set; }
        public Nullable<bool> tieneActa { get; set; }
        public Nullable<bool> tieneContrato { get; set; }
    }
}
