//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_meieEntities : DbContext
    {
        public db_meieEntities()
            : base("name=db_meieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GrlDepartament> GrlDepartament { get; set; }
        public virtual DbSet<LicActaEstado> LicActaEstado { get; set; }
        public virtual DbSet<LicActaGenerica> LicActaGenerica { get; set; }
        public virtual DbSet<LicActaObra> LicActaObra { get; set; }
        public virtual DbSet<LicArchivoCategoria> LicArchivoCategoria { get; set; }
        public virtual DbSet<LicArchivoEmpresa> LicArchivoEmpresa { get; set; }
        public virtual DbSet<LicArchivoEstado> LicArchivoEstado { get; set; }
        public virtual DbSet<LicCalificacionChatbot> LicCalificacionChatbot { get; set; }
        public virtual DbSet<LicChatbot> LicChatbot { get; set; }
        public virtual DbSet<LicConsultas> LicConsultas { get; set; }
        public virtual DbSet<LicDocGeneral> LicDocGeneral { get; set; }
        public virtual DbSet<LicDocObra> LicDocObra { get; set; }
        public virtual DbSet<LicDocSobres> LicDocSobres { get; set; }
        public virtual DbSet<LicEmail> LicEmail { get; set; }
        public virtual DbSet<LicEmpresaHabilitada> LicEmpresaHabilitada { get; set; }
        public virtual DbSet<LicEmpresaObra> LicEmpresaObra { get; set; }
        public virtual DbSet<LicEscenarioChatbot> LicEscenarioChatbot { get; set; }
        public virtual DbSet<LicOferta> LicOferta { get; set; }
        public virtual DbSet<LicOfertaEmpresa> LicOfertaEmpresa { get; set; }
        public virtual DbSet<LicOfertaEstado> LicOfertaEstado { get; set; }
        public virtual DbSet<LicProyecto> LicProyecto { get; set; }
        public virtual DbSet<LicProyectoFecha> LicProyectoFecha { get; set; }
        public virtual DbSet<OficinaMunicipio> OficinaMunicipio { get; set; }
        public virtual DbSet<PryEspecialidad> PryEspecialidad { get; set; }
        public virtual DbSet<PryFinanciacion> PryFinanciacion { get; set; }
        public virtual DbSet<PryFuentesFinanciamiento> PryFuentesFinanciamiento { get; set; }
        public virtual DbSet<PryOrganismosEjecutores> PryOrganismosEjecutores { get; set; }
        public virtual DbSet<PryProyecto> PryProyecto { get; set; }
        public virtual DbSet<PryProyectoEspecialidad> PryProyectoEspecialidad { get; set; }
        public virtual DbSet<PryProyectoEstado> PryProyectoEstado { get; set; }
        public virtual DbSet<PryProyectoEtapa> PryProyectoEtapa { get; set; }
        public virtual DbSet<PryProyectoMunicipio> PryProyectoMunicipio { get; set; }
        public virtual DbSet<PryProyectoOrganismoEjecutor> PryProyectoOrganismoEjecutor { get; set; }
        public virtual DbSet<PryProyectoSubEspecialidad> PryProyectoSubEspecialidad { get; set; }
        public virtual DbSet<PrySubEtapa> PrySubEtapa { get; set; }
        public virtual DbSet<SegAccess> SegAccess { get; set; }
        public virtual DbSet<SegAutoUser> SegAutoUser { get; set; }
        public virtual DbSet<SegOffice> SegOffice { get; set; }
        public virtual DbSet<SegPassword> SegPassword { get; set; }
        public virtual DbSet<SegProfile> SegProfile { get; set; }
        public virtual DbSet<SegProfileAccess> SegProfileAccess { get; set; }
        public virtual DbSet<SegTitulo> SegTitulo { get; set; }
        public virtual DbSet<SegUser> SegUser { get; set; }
        public virtual DbSet<SegUserProfile> SegUserProfile { get; set; }
        public virtual DbSet<SegUserTitulo> SegUserTitulo { get; set; }
        public virtual DbSet<SegUserVisualiza> SegUserVisualiza { get; set; }
        public virtual DbSet<UfiOrgano> UfiOrgano { get; set; }
        public virtual DbSet<UfiOrganoOficina> UfiOrganoOficina { get; set; }
        public virtual DbSet<PryEstadoEtapa> PryEstadoEtapa { get; set; }
        public virtual DbSet<PryLicitacion> PryLicitacion { get; set; }
        public virtual DbSet<GrlType> GrlType { get; set; }
        public virtual DbSet<PryProyectoPlanificacion> PryProyectoPlanificacion { get; set; }
        public virtual DbSet<PrySubEspecialidad> PrySubEspecialidad { get; set; }
        public virtual DbSet<AudAccion> AudAccion { get; set; }
        public virtual DbSet<AudLogAccion> AudLogAccion { get; set; }
        public virtual DbSet<PryAuditoria> PryAuditoria { get; set; }
        public virtual DbSet<LicArchivoObra> LicArchivoObra { get; set; }
    }
}
