//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class PryAuditoria
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public string modificacion { get; set; }
        public Nullable<int> idPryProyecto { get; set; }
        public Nullable<int> idAudLogAccion { get; set; }
    
        public virtual AudLogAccion AudLogAccion { get; set; }
    }
}
