//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class PryProyectoEspecialidad
    {
        public int id { get; set; }
        public int idPryEspecialidad { get; set; }
        public int idPryProyecto { get; set; }
        public Nullable<int> porcentaje100to400 { get; set; }
        public Nullable<int> porcentaje500 { get; set; }
    }
}
