//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_RACOPEntities : DbContext
    {
        public DB_RACOPEntities()
            : base("name=DB_RACOPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<rc_Audit> rc_Audit { get; set; }
        public virtual DbSet<rc_AuditActions> rc_AuditActions { get; set; }
        public virtual DbSet<rc_AuditDetalle> rc_AuditDetalle { get; set; }
        public virtual DbSet<rc_Empresa> rc_Empresa { get; set; }
        public virtual DbSet<rc_User> rc_User { get; set; }
        public virtual DbSet<rc_EmpresaUser> rc_EmpresaUser { get; set; }
    }
}
