//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class rc_Audit
    {
        public int id { get; set; }
        public int IdUserEmpresa { get; set; }
        public string Data { get; set; }
        public System.DateTime FechaHora { get; set; }
        public int idAuditActions { get; set; }
    }
}
