//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class rc_Empresa
    {
        public int idEmpresa { get; set; }
        public string cuit { get; set; }
        public string nro { get; set; }
        public string password { get; set; }
        public string razonSocial { get; set; }
        public string ingresosBrutos { get; set; }
        public string inscripcionIERIC { get; set; }
        public string inscConsejoNro { get; set; }
        public Nullable<System.DateTime> inscConsejoFecha { get; set; }
        public string domicilioReal { get; set; }
        public string telefono { get; set; }
        public string esMendocina { get; set; }
        public System.DateTime inscRegSocietario { get; set; }
        public string domicilioEspecial { get; set; }
        public string telefonoEspecial { get; set; }
        public string mailEspecial { get; set; }
        public string nomApeContacto { get; set; }
        public string telefonoContacto { get; set; }
        public string mailContacto { get; set; }
        public string passTokenRecovery { get; set; }
        public string activo { get; set; }
        public string firmaDigital { get; set; }
        public string estadoBloqueo { get; set; }
    }
}
