//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class rc_EmpresaUser
    {
        public int id { get; set; }
        public int idEmpresa { get; set; }
        public int idUser { get; set; }
        public int activo { get; set; }
        public int usuarioCarga { get; set; }
        public string fechaAlta { get; set; }
        public string fechaBaja { get; set; }
        public int Id_rol { get; set; }
    }
}
