//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class rc_User
    {
        public int idUser { get; set; }
        public string cuil { get; set; }
        public string nombreApellido { get; set; }
        public string telefono { get; set; }
        public string mail { get; set; }
        public string pasword { get; set; }
        public string lastLogIn { get; set; }
        public int activo { get; set; }
        public string passTokenRecovery { get; set; }
    }
}
