//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegAutoUser
    {
        public int Id { get; set; }
        public int User_Id { get; set; }
        public int StateType_ID { get; set; }
        public string MotivoDeRegistro { get; set; }
        public string NumeroContacto { get; set; }
    }
}
