//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegOffice
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int State_Type_Id { get; set; }
        public string Code { get; set; }
        public string Office { get; set; }
        public string Telephone { get; set; }
        public Nullable<int> Nivel { get; set; }
        public sbyte Eliminado { get; set; }
        public Nullable<int> idOfficePadre { get; set; }
    }
}
