//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licitaciones.BaseDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegPassword
    {
        public int Id { get; set; }
        public int SegUser_Id { get; set; }
        public string Hash { get; set; }
        public int Secuence { get; set; }
        public System.DateTime Date { get; set; }
    }
}
